### ISSUE TITLE
How can I change crop option from square to circle?

### ISSUE THREAD

**Issue by Bhumika801** [pavlik111188/angular-image-editor#1]
When we select the image to crop then crop option comes in square how can I change it in circle?

**Comment by pavlik111188** [comment]
@Bhumika801 unfortunately we have no this feature yet.

**Comment by Bhumika801** [comment]
But I think I have solved the issue and it's working fine now.

**Comment by pavlik111188** [comment]
@Bhumika801 Great, could you share?
